### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jakubfabijan** [De7vID/klingon-assistant-android#103]
Any plans for multilanguage support?

**Comment by De7vID** [comment]
Can you be more specific about what you mean?

If this is about the database, it already supports many languages (but no new languages will be added at this time):
https://github.com/De7vID/klingon-assistant/issues/462

If this is about the Android app's UI language, feel free to submit pull requests for the files here:
https://github.com/De7vID/klingon-assistant-android/tree/master/app/src/main/res

(There's also an iOS port here: https://github.com/dadap/flingon-assister)
